name: Build Laravel Dependencies

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, openssl, pdo, tokenizer, xml, ctype, curl, zip, sodium
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Cache vendor folder
      uses: actions/upload-artifact@v4
      with:
        name: vendor
        path: vendor/
