name: Save vendor

on:
  push:
    branches:
      - dev  # ou 'main', se quiser rodar quando fizer push na main

jobs:
  zip-vendor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, openssl, pdo, tokenizer, xml, ctype, curl, zip, sodium
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Zip vendor folder
        run: zip -r vendor-vendor.zip vendor

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vendor-vendor
          path: vendor-vendor.zip
